# Generated by Django 5.0.6 on 2024-06-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbatchstock',
            options={'verbose_name': 'Saldo por Lote', 'verbose_name_plural': 'Saldos por Lote'},
        ),
    ]
