# Generated by Django 5.0.6 on 2024-06-24 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_processbatchstage_quantity_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_balances', to='products.product', to_field='sku')),
            ],
            options={
                'verbose_name': 'Saldo de Distribuição',
                'verbose_name_plural': 'Saldos de Distribuição',
            },
        ),
    ]
